name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  script: # change this
    required: true
    description: 'name of a script in your ./scripts dir'
runs:
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
    main: 'dist/index.js'
