name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  script: # change this
    required: true
    description: 'name of a script in your ./scripts dir'
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
    - run: |
        echo Script: ${{ inputs.script }}.
        echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - uses: actions/checkout@v2
    - run: |
        mkdir node
        ./install-node.sh --prefix ./node
        echo "./node/bin" >> $GITHUB_PATH
        echo $GITHUB_PATH
      shell: bash
    - run: |
        which node
        node --version
      shell: bash
    - run: |
        npm i
        npm run build
        npm run package
        node ./dist/index.js --script ${{ inputs.script }}
      shell: bash
