name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        node_dir="$(dirname -- "$(realpath -- ".")")/node"
        mkdir $node_dir
        echo $node_dir
        ./install-node.sh --prefix $node_dir
        echo "$node_dir/bin" >> $GITHUB_PATH
      shell: bash
    - run: |
        which node
        node --version
      shell: bash
    - run: |
        npm i -g @johnlindquist/kit@alpha
        which kit
        kit ${{ inputs.script }}
      shell: bash
