name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
  args:
    required: false
    description: "args to pass to the script"

outputs:
  result:
    description: "result of the script args"
    value: ${{ steps.script-kit.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Script Kit running ${{ inputs.script }}
      id: script-kit
      run: |

        kit_dir="$HOME/.kit"
        node_dir="$HOME/.knode"

        echo "$node_dir/bin" >> $GITHUB_PATH

        kit_node="$node_dir/bin/node"
        kit_npm="$node_dir/bin/npm"

        echo "kit_node: $kit_node"
        echo "kit_npm: $kit_npm"

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        echo "KIT_NODE: $KIT_NODE"
        echo "KIT: $KIT"

        mkdir -p $node_dir
        mkdir -p $kit_dir

        # Install node 16.14.2 if it doesn't exist   
        if [ "$RUNNER_OS" = "Windows" ]; then
          [ ! -d "$node_dir/bin" ] && curl -sfLS https://install-node.vercel.app/v16.17.1 | bash -s -- -f --platform win --arch x64 --prefix $node_dir
        else
          [ ! -d "$node_dir/bin" ] && curl -sfLS https://install-node.vercel.app/v16.17.1 | bash -s -- -f --prefix $node_dir
        if        

        echo "Installing @johnlindquist/kit to $kit_dir"
        $kit_npm i -D --prefix $kit_dir @johnlindquist/kit

        # cat the $kit_dir package.json
        cat $kit_dir/package.json

        $kit_node --version

        # Get the repo name from the github context
        repo_name=$(echo "${{ github.repository }}" | cut -d "/" -f 2)

        export KENV="$HOME/work/$repo_name/$repo_name"

        # cd into the scripts dir
        cd $KENV/scripts

        # if scripts/package.json doesn't exist, init
        [ ! -f "package.json" ] && $kit_npm init es6 -y

        kenv_scripts=$KENV/scripts

        echo "Linking kit dir $KIT to $kenv_scripts"
        $kit_npm i -D --prefix $kenv_scripts $KIT

        echo "Installing @actions/github to $kenv_scripts"
        $kit_npm i -D --prefix $kenv_scripts @actions/github

        echo "Installing @actions/core to $kenv_scripts"
        $kit_npm i -D --prefix $kenv_scripts @actions/core

        # cat the scripts package.json
        cat $kenv_scripts/package.json
        # ls the node_modules
        ls $kenv_scripts/node_modules

        # cd back to the $KENV dir
        cd $KENV

        # If package.json doesn't exist, init
        [ ! -f "package.json" ] && $kit_npm init es6 -y

        echo "🏃‍♀️ Running: ${{ inputs.script }} ${{ inputs.args }}"

        SCRIPTS_DIR=${SCRIPTS_DIR:-scripts} $kit_node $KIT/run/github-workflow.js ${{ inputs.script }} ${{ inputs.args }} --trust

      shell: bash
