name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  script: # change this
    required: true
    description: 'name of a script in your ./scripts dir'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: |
        curl -sL install-node.vercel.app/v16.9.1 | sh
      shell: bash
    - run: |
        which node
        node --version
      shell: bash
