name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
  args:
    required: false
    description: "args to pass to the script"
outputs:
  result:
    description: "result of the script args"
    value: ${{ steps.script-kit.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - id: script-kit
      run: |
        node_dir="$HOME/node"
        kit_dir="$HOME/kit"

        kit_node="$node_dir/bin/node"
        kit_npm="$node_dir/bin/npm"

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        mkdir $node_dir
        mkdir $kit_dir

        find / -name "install.sh"

        "$HOME/kit-action/kit-action/install-node.sh" --prefix $node_dir

        $kit_npm i --prefix $kit_dir @johnlindquist/kit@alpha

        # echo "😊"      
        # echo "$KIT_NODE"
        # echo "$KIT"
        ls ./scripts

        cat $KIT/script

        # echo "👀"

        # echo "INPUTS SCRIPT: ${{ inputs.script }}"

        # echo "./scripts/${{ inputs.script }}.js"

        # echo "🧁 cat test-script"
        cat "./scripts/${{ inputs.script }}.js"

        result=$($KIT/bin/k "${{ inputs.script }}" "${{ inputs.args }}")
        echo "::set-output name=result::$result"
      shell: bash

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
