name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  script: # change this
    required: true
    description: 'name of a script in your ./scripts dir'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir node
        ./install-node.sh --prefix ./node
        echo "./node/bin" >> $GITHUB_PATH
        echo $GITHUB_PATH
      shell: bash
    - run: |
        which node
        node --version
      shell: bash
    - run: |
        npm i
        npm run build
        npm run package
        node ./dist/index.js
      shell: bash
