name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        ls .
        parent_dir=$(dirname -- "$(realpath -- ".")")
        echo "PARENT DIR: $HOME"
        node_dir="$parent_dir/node"
        mkdir $node_dir
        echo "NODE DIR: $node_dir"
        ./install-node.sh --prefix $node_dir

        kit_dir="$parent_dir/kit"
        mkdir $kit_dir

        kit_node="$node_dir/bin/node"
        kit_npm="$node_dir/bin/npm"

        $kit_npm i --prefix $kit_dir @johnlindquist/kit@alpha

        echo "😅"
        echo $PWD

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        echo "😊"      
        echo $KIT_NODE
        echo $KIT

        "$KIT/bin/k" "./scripts/${{ inputs.script }}.js"
      shell: bash
