name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
  args:
    required: false
    description: "args to pass to the script"

outputs:
  result:
    description: "result of the script args"
    value: ${{ steps.script-kit.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3 # Checkout this project (including ./scripts dir)
    - name: Script Kit running ${{ inputs.script }}
      id: script-kit
      run: |

        kit_dir="$HOME/.kit"
        node_dir="$HOME/.knode"

        echo "$node_dir/bin" >> $GITHUB_PATH

        kit_node="$node_dir/bin/node"
        kit_npm="$node_dir/bin/npm"

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        mkdir -p $node_dir
        mkdir -p $kit_dir

        # Install node 16.14.2 if it doesn't exist    
        [ ! -d "$node_dir/bin" ] && curl -sfLS https://install-node.vercel.app/v16.14.2 | bash -s -- -f --prefix $node_dir

        echo "Installing @johnlindquist/kit to $kit_dir"
        $kit_npm i -D --prefix $kit_dir @johnlindquist/kit

        # cat the $kit_dir package.json
        cat $kit_dir/package.json

        $kit_node --version

        # Get the repo name from the github context
        repo_name=$(echo "${{ github.repository }}" | cut -d "/" -f 2)

        export KENV="$HOME/work/$repo_name/$repo_name"
        cd $KENV/scripts

        echo "Creating $kit_npm/package.json"
        $kit_npm init es6 -y

        kenv_scripts=$KENV/scripts

        echo "Installing @actions/github to $kenv_scripts"
        $kit_npm i -D --prefix $kenv_scripts @actions/github

        echo "Installing @actions/core to $kenv_scripts"
        $kit_npm i -D --prefix $kenv_scripts @actions/core

        # cat the scripts package.json
        cat $kenv_scripts/package.json
        # ls the node_modules
        ls $kenv_scripts/node_modules

        cd $KENV

        # If package.json doesn't exist, init
        [ ! -f "$KENV/package.json" ] && $kit_npm init es6 -y

        echo "🏃‍♀️ Running: ${{ inputs.script }} ${{ inputs.args }}"

        KIT_CONTEXT="github-workflow" $kit_node $KIT/run/github-workflow.js ${{ inputs.script }} ${{ inputs.args }} --trust
      shell: bash
