name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
  args:
    required: false
    description: "args to pass to the script"
outputs:
  result:
    description: "result of the script args"
    value: ${{ steps.script-kit.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2 # Checkout this project (including ./scripts dir)

    - name: Add node to PATH
      run: |
        echo "$HOME/.kit/node/bin:$HOME/.kit/bin" >> $GITHUB_PATH
      shell: bash

    - name: Script Kit running ${{ inputs.script }}
      id: script-kit
      run: |
        kit_dir="$HOME/.kit"
        node_dir="$HOME/.kit/node"


        kit_node="$node_dir/bin/node"
        kit_npm="$node_dir/bin/npm"

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        mkdir -p $node_dir
        mkdir -p $kit_dir

        [ ! -d "$node_dir/bin" ] && curl -sfLS https://install-node.vercel.app/v17.1.0 | bash -s -- -f --prefix $node_dir
        $kit_npm i --prefix $kit_dir @johnlindquist/kit@beta
        $kit_npm i --prefix $kit_dir -D @actions/github

        # echo $PATH
        $kit_node --version

        # find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/" 

        export KENV="$HOME/work/${{ env.GITHUB_REPOSITORY_NAME_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}"
        cd $KENV

        # find $project_dir | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/" 
        export KIT_NODE_PATH="$HOME/node/bin"
        result=$($KIT/bin/k "${{ inputs.script }}" "${{ inputs.args }}" --trust)
        echo "::set-output name=result::$result"
      shell: bash

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
