name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
  args:
    required: false
    description: "args to pass to the script"

outputs:
  result:
    description: "result of the script args"
    value: ${{ steps.script-kit.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.1

    - name: Script Kit running ${{ inputs.script }}
      id: script-kit
      run: |

        kit_dir="$HOME/.kit"
        node_dir=$(which node | xargs dirname | xargs dirname)

        echo "kit_node: $kit_node"

        export KIT_NODE="$kit_node"        
        export KIT="$kit_dir/node_modules/@johnlindquist/kit"  

        echo "KIT_NODE: $KIT_NODE"
        echo "KIT: $KIT"

        mkdir -p $kit_dir     

        echo "Installing @johnlindquist/kit to $kit_dir"
        npm i -D --prefix $kit_dir @johnlindquist/kit

        # cat the $kit_dir package.json
        cat $kit_dir/package.json

        node --version

        # Get the repo name from the github context
        repo_name=$(echo "${{ github.repository }}" | cut -d "/" -f 2)

        export KENV="$GITHUB_WORKSPACE"

        # cd into the scripts dir
        cd $KENV/scripts

        # if scripts/package.json doesn't exist, init
        # [ ! -f "package.json" ] &&
        npm init es6 -y

        kenv_scripts=$KENV/scripts

        echo "Linking kit dir $KIT to $kenv_scripts"
        npm i -D --prefix $kenv_scripts $KIT

        echo "Installing @actions/github to $kenv_scripts"
        npm i -D --prefix $kenv_scripts @actions/github

        echo "Installing @actions/core to $kenv_scripts"
        npm i -D --prefix $kenv_scripts @actions/core

        # cat the scripts package.json
        cat $kenv_scripts/package.json
        # ls the node_modules
        ls $kenv_scripts/node_modules

        # cd back to the $KENV dir
        cd $KENV

        # If package.json doesn't exist, init
        [ ! -f "package.json" ] && npm init es6 -y

        echo "🏃‍♀️ Running: ${{ inputs.script }} ${{ inputs.args }}"

        # If SCRIPTS_DIR is not set, set it to scripts
        if [ -z "$SCRIPTS_DIR" ]; then
          export SCRIPTS_DIR=scripts
        fi

        node $KIT/run/github-workflow.js ${{ inputs.script }} ${{ inputs.args }} --trust

      shell: bash
