name: "Script Kit Action"
description: "Uses @johnlindquist/kit to run a script"
author: "John Lindquist"
inputs:
  script:
    required: true
    description: "name of a script in your ./scripts dir"
runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: "johnlindquist/kit"
        ref: "alpha"
        path: ".kit"
    - run: |
        echo ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
        ls ./*/*
        ls ./.kit
        echo "Workspace: ${{ github.workspace }}""
        ls "${{ github.workspace }}/.kit"
        ./.kit/build/build-kit.sh
      shell: bash
    - run: |
        ./.kit/bin/k ${{ inputs.script }}
      shell: bash
